package:
  name: cryptography
  version: 41.0.4

{% if version and version < (3, 4, 9) %}

patches:
  - random.patch

build:
  script_env:
    - CRYPTOGRAPHY_DONT_BUILD_RUST=1

requirements:
  build:
    - cffi 1.15.1
    - setuptools-rust 0.11.6
  host:
    - openssl 1.1.1v

{% else %}

patches:
  - mobile.patch

build:
  script_env:
    - OPENSSL_STATIC=1
    - OPENSSL_DIR={platlib}/opt

requirements:
  build:
    - setuptools_rust @ git+https://github.com/freakboy3742/setuptools-rust@iOS-support
  host:
    - openssl 3.1.2

{% endif %}
