package:
  name: libjpeg
  version: 1.5.3

source:
  url: https://github.com/libjpeg-turbo/libjpeg-turbo/releases/download/{version}/libjpeg-turbo-{version}.tar.gz

patches:
  - config.patch

build:
  number: 1
